---
kind: pipeline
type: docker
name: CI

steps:
- name: Build and Push Image
  image: plugins/docker
  settings:
    auto_tag: true
    dry_run: true
    no_cache: true
    debug: true
    context: vote
    dockerfile: vote/Dockerfile
    repo: dhavlev
    registry: registry.hub.docker.com
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password



